routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//  Admin panel routes start
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/category','Admin\CategoryController');
Route::resource('/brand','Admin\BrandController');
Route::resource('/product','Admin\ProductController');
//  Admin panel routes end

Route::get('/shops/{id}','Shop\ShopController@index')->name('shop');

Route::get('/layout',function (){ return view('layout');})->name('layout');
Route::get('layout/{id}/{shop}','Shop\ShopController@updateLayout');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;




Route::domain('test1234.ecommerce.com')->group(function () {
    Route::get('/shops/{id}','Shop\ShopController@index')->name('shop');
    //Route::get('/','Shop\ShopController@index')->name('shop');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    //
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uuid','name',
    ];
    /**
     * Get the brands.
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','product_image', 'category_id', 'brand_id', 'product_price_id', 'product_uid', 'name', 'description',
    ];

    /**
     * Get the categories.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the Product .
     */
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

     /**
     * Get the Product .
     */
    public function productPrice()
    {
        return $this->belongsTo(ProductPrice::class);
    }

    /**
     * Get the categories.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Brand;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::paginate(10);
        return view('products.brand.show-brand',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.brand.create-brand');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'=>['required']
        ]);
        $uuid = base64_encode(openssl_random_pseudo_bytes(10));
        $brands = Brand::create(['uuid'=>$uuid,'name'=>$request->brand]);
        return back()->with('message','Category Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        $brands = Brand::where('uuid',$uuid)->first();
        return view('products.brand.edit-brand',compact('brands'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $uuid)
    {
        $brands = Brand::where('uuid',$uuid)->update(['name'=>$request->brand]);
        if ($brands) {
            return redirect('/brand')->with('message','Brand Updated Successfully');
        } else {
            return redirect('/brand')->with('error','Not updated Something Wrong!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Traits\UploadImageTrait;
use App\Category;
use App\Brand;
use App\Product;
use App\ProductPrice;
use Image;
use Auth;

class ProductController extends Controller
{
    use UploadImageTrait;

    protected $photo = 'photo';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('category','brand','productPrice')->get();
        return view('products.manage-product',compact('products'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('products.create',compact('categories','brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $productPrices = ProductPrice::create([
            'purchase_price'=>$request->purchaseprice,
            'sell_price'=>$request->sellprice
        ]);
        if ($productPrices) {
        $products = new Product;
        $products->fill($request->all());
        if (!empty($request->image)){
            $image       = $request->file('image');
            $filename = time().mt_rand(100000, 999999).'.'.$image ->getClientOriginalExtension();
            Image::make($image)->save(public_path('upload/'.$filename)); // put in Job Queue
            $file_path = '/upload/'.$filename;
        }
        $products = Product::create([
            'user_id' => Auth::user()->id,
            'product_image' => $file_path,
            'category_id' => $request->category,
            'brand_id' => $request->brand,
            'name' => $request->productname,
            'product_uid' => $request->productid,
            'description' => $request->get('description'),
            'product_price_id' => $productPrices->id
        ]);
        if ($products) {
          return redirect('/product');
        }
      } else {
          return back();
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/products/brand/create-brand.blade.php
@extends('layouts.admin.main')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3>Add Brand Form</h3>
                <div class="card">
                    <div class="card-header bg-orange text-white">
                        Brand Form
                    </div>
                    <div class="card-body">
                        <form  method="POST" action="{{route('brand.store')}}">
                            {{csrf_field()}}
                            <div class="row justify-content-center">
                                <div class="col-sm-6">
                                    <input type="text" name="brand" class="form-control" placeholder="category name" required>
                                </div>
                                <input type="submit" value="Save category">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/brand/edit-brand.blade.php
@extends('layouts.admin.main')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3>Add Category Form</h3>
                <div class="card">
                    <div class="card-header bg-orange text-white">
                        Category Form
                    </div>
                    <div class="card-body">
                        <form  method="POST" action="{{route('brand.update',$brands->uuid)}}">
                            {{ method_field('PUT') }}
                            {{csrf_field()}}
                            <div class="row justify-content-center">
                                <div class="col-sm-6">
                                    <input type="text" name="brand" class="form-control" value="{{$brands->name}}">
                                </div>
                                <input type="submit" value="update category">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/brand/show-brand.blade.php
@extends('layouts.admin.main')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3>Brands</h3>
                @if (session()->has('error'))
                    <div  class="alert alert-danger">
                        {{session()->get('error')}}
                    </div>
                @endif
                <div id="Message">
                    @if (session()->has('message'))
                        <div  class="alert alert-info">
                            {{session()->get('message')}}
                        </div>
                    @endif
                </div>
                <a href="{{route('brand.create')}}"><button class="btn btn-md btn-success pull-right">Add Brand</button></a>
                <div class="card">
                    <div class="card-header bg-orange text-white">
                       Brands
                    </div>

                    <div class="card-body">
                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            @foreach( $brands as $brand)
                                <tbody>
                                <tr>
                                    <td>{{$brand->uuid}}}</td>
                                    <td>{{$brand->name}}</td>
                                    <td>
                                        <a href="{{route('brand.edit',$brand->uuid)}}"><button class="btn btn btn-sm btn-info">Edit</button></a>
                                        <a href=""><button class="btn btn btn-sm btn-danger">Del</button></a>
                                    </td>
                                </tr>
                                </tbody>
                            @endforeach
                        </table>
                        {{$brands->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection