routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//  Admin panel routes start
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/category','Admin\CategoryController');
Route::resource('/brand','Admin\BrandController');
Route::resource('/product','Admin\ProductController');
//  Admin panel routes end

Route::get('/shops/{id}','Shop\ShopController@index')->name('shop');

Route::get('/layout',function (){ return view('layout');})->name('layout');
Route::get('layout/{id}/{shop}','Shop\ShopController@updateLayout');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;




Route::domain('test1234.ecommerce.com')->group(function () {
    Route::get('/shops/{id}','Shop\ShopController@index')->name('shop');
    //Route::get('/','Shop\ShopController@index')->name('shop');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','product_image', 'category_id', 'brand_id', 'product_price_id', 'product_uid', 'name', 'description',
    ];

    /**
     * Get the categories.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the Product .
     */
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

     /**
     * Get the Product .
     */
    public function productPrice()
    {
        return $this->belongsTo(ProductPrice::class);
    }

    /**
     * Get the categories.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Traits\UploadImageTrait;
use App\Category;
use App\Brand;
use App\Product;
use App\ProductPrice;
use Image;
use Auth;

class ProductController extends Controller
{
    use UploadImageTrait;

    protected $photo = 'photo';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('category','brand','productPrice')->get();
        return view('products.manage-product',compact('products'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('products.create',compact('categories','brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $productPrices = ProductPrice::create([
            'purchase_price'=>$request->purchaseprice,
            'sell_price'=>$request->sellprice
        ]);
        if ($productPrices) {
        $products = new Product;
        $products->fill($request->all());
        if (!empty($request->image)){
            $image       = $request->file('image');
            $filename = time().mt_rand(100000, 999999).'.'.$image ->getClientOriginalExtension();
            Image::make($image)->save(public_path('upload/'.$filename)); // put in Job Queue
            $file_path = '/upload/'.$filename;
        }
        $products = Product::create([
            'user_id' => Auth::user()->id,
            'product_image' => $file_path,
            'category_id' => $request->category,
            'brand_id' => $request->brand,
            'name' => $request->productname,
            'product_uid' => $request->productid,
            'description' => $request->get('description'),
            'product_price_id' => $productPrices->id
        ]);
        if ($products) {
          return redirect('/product');
        }
      } else {
          return back();
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/products/create.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="container-fluid">
  <div class="row">
       <div class="col-md-12">
          <h3>Add Products Form</h3>
            <div class="card">
                <div class="card-header bg-dark text-white">
                    Products Form
                </div>
                <div class="card-body">
                    <form  method="POST" action="{{route('product.store')}}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="row">
							<div class="col-sm-6">
                                <select name="category" id="" class="form-control" value="{{ old('category') }}" required>
                                    <option value="">---choose category----</option>
                                    @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
							</div>
							<div class="col-sm-6">
                                <select name="brand" id="" class="form-control" value="{{ old('brand') }}"  required>
                                    <option value="">---choose brand---</option>
                                    @foreach($brands as $brand)
                                    <option value="{{$brand->id}}">{{$brand->name}}</option>
                                    @endforeach
                                </select>
							</div>
						</div>
                        <div class="row">
							<div class="col-sm-6">
                                <input type="text" class="form-control" value="{{ old('productid') }}"  name ="productid" placeholder="product id" required>
							</div>
                            <div class="col-sm-6">
                                <input type="text" name="productname" class="form-control" placeholder="product name" value="{{ old('productname') }}" placeholder="product name" required>
							</div>
						</div>
                        <div class="row">
							<div class="col-sm-6">
                                 <input type="text" class="form-control" value="{{ old('productid') }}"  name ="purchaseprice" placeholder="product purchase price" required>
							</div>
                            <div class="col-sm-6">
                                 <input type="text" name="sellprice" class="form-control" placeholder="product name" value="{{ old('productname') }}" placeholder="product sell price" required>
							</div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input type="file" name="image"  required>
                            </div>
                        </div>
                        <div class="row">
                          <div class="col-md-12">
                              <textarea class="description form-control"  name="description" value="{{ old('description') }}" required>
                              </textarea>
                          </div>
                        </div>
                        <input type="submit" value="Save Product">
                    </form>
                </div>
            </div>
        </div>
  </div>
</div>
<script src="{{ asset('node_modules/tinymce/tinymce.js') }}"></script>
<script>
    tinymce.init({
        selector:'textarea.description',
        height: 300
    });
</script>
@endsection

resources/views/products/manage-product.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="container-fluid">
  <div class="row">
       <div class="col-md-12">
          <h3>Products</h3>
             <div class="card-header bg-dark text-white">
                  Products
                  <a href="{{route('product.create')}}"><button class="btn btn-success btn-md float-right">Add New</button></a>
             </div>
              <div class="card-body">
              <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Category</th>
                            <th>Brand</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>SellPrice</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    @foreach( $products as $product)
                    <tbody>
                      <tr>
                          <td>{{$product->product_uid}}</td>
                          <td><img src="{{$product->product_image}}" alt="" height="50" width="50"></td>
                          <td>{{$product->category->name}}</td>
                          <td>{{$product->brand->name}}</td>
                          <td>{{$product->name}}</td>
                          <td>{{$product->description}}</td>
                          <td>{{$product->productPrice->sell_price}}</td>
                          <td>
                              <a href=""><button class="btn btn btn-sm btn-info">Edit</button></a>
                              <a href=""><button class="btn btn btn-sm btn-danger">Del</button></a>
                          </td>
                      </tr>
                    </tbody>
                  @endforeach
                    </table>
              </div>
           </div>
       </div>
  </div>
</div>
@endsection

resources/views/products/show-product.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="container bg-white">
    <div class="row">
        <div class="col-md-12">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
          <thead>
              <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Action</th>
              </tr>
          </thead>
          @foreach( $brands as $brand )
          <tbody>
             <tr> 
                <td>{{$brand->uuid}}</td>
                <td>{{$brand->name}}</td>
                <td> 
                   <div class="group pull-right">
                    <u><a href="">new sub-category</a></u> |
                    <u><a href="">upload picture</a></u>
                   <a href=""><button class="btn btn-sm btn-info">View</button></a>
                   <a  data-toggle="modal" data-target="#modalCategoryEdit"><button class="btn btn-sm btn-primary">Edit</button></a>
                   <a href=""><button class="btn btn-sm btn-danger">Del</button></a>
                   </div>
                </td>
             </tr>
          </tbody>
          @endforeach
        </table>
        </div>
    </div>
</div>


@endsection